-- Plain inserts: no IF blocks, no variables
USE dbLabCenter;

-- Borrowers
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jonathan','Ehlman','726743','5135691762',NULL,'Me',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('"','Wagner','588443','5135694684',NULL,'"',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Clarance','Stepp','475875','5134043749',NULL,'Singleton',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Clarence Stepp');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jessica','Cortez','704399','8315393969',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Jess Cortez');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Ryan','Kellam','706770','8599574988',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Quintan','Mincy','632672','5135212381',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Andrew','Moreland','709786','5134390915',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Andrew Morlan');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('William','Smith','678189','5136090114',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Will Smith');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Spencer','Spek','683043','9377169020',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Bryce','Washick','587445','5136578913',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Ben','Wylie','587114','5135703925',NULL,'Ron',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Ben Wiley');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Da''Quan','Allen','696703','5136044591',NULL,'Singleton',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Daquan Allen');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Donald','Brill','483907','5139394863',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Kantima','Egngtion','695527','5133645302',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Mickaela','Harris','620929','5136923731',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Mikayla Harris');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Quintanilla','Karen','716176',NULL,NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Moussa','Kebe','702088','5133061094',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Mussa Kebe');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Erin','Moeller','700224','5138691177',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Erin Molar');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Evan','Sellers','696723','5133029660',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Evan Selles');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Tanner','Sharpe','679236','6125977447',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Joey','Tomamichel','701563','5132888539',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Wesley','Ortiz','703415','5137870377',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Alexander','Bozhenov','702964','5138008247',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Andrew','Day','507792','8594443756',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Mason','Earls','716207','8126554677',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Max','Hall','716944','5138052605',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Max Paul');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Damen','Madaris','719233','5133745236',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Damaind Madaris');
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Damon Madaris');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Cole','Quitter','680317','8596384570',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Tanner','Thornberry','709999','8596401274',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Minaj','Waeba','706645','5133061948',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Manoj Waiba');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Katie','Wernicke','683161','5134622229',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('John','Wilson','704343','8596200250',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Andrew','Slipper','717574','9377059811',NULL,'Curtis',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Andrew Sliper');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Sam','Beccaccio','730163','8594625058',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Kyle','Hedlund','664114','8596355325',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jorden','Hess','709439','5134447808',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Galyam','Korbogo','725150','5139788988',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Galyam Korbeogo');
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Galyan Korbeogo');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Sean','Miller','303364','5136687423',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Tyler','Miller','506049','5132892108',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Simon','Valdez','717461','8592409186',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Noah','Patsfall','658471','5138465118',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jasmine','Hurst','495148','7049073211',NULL,'-',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Alex','Masraum','699106','5134707774',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Isabella','Carmen','706242','5134977066',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Joshua','Hoffman','739273','5136874090',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Quincy','Milton','598689','5136162311',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Dakota','Risch','682898','5134176479',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jacob','Steinmetz','732516','2166443967',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Aaron','Arocho','671792','5132541498',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Zemirah','Torrey','680996','5136550954',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Collin','Mccloy','738133','5134796857',NULL,'Curtis',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Colin Mccloy');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Andrew','Osburg','664251','8596405563',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Rathana','Kreal','151430','5134070607',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Nelson','Makada','711504','5134790684',NULL,'Curtis',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Nelson Malakada');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Garrett','Hornsby','716991','5133004346',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jarod','Moore','707595','5135756735',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Jared Moore');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jonathan','Nemi','731814','7169400074',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Nicholas','Odgers','695941','5136784837',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Justin','Owens','708026','5133165228',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Jackson Owens');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Tyler','Vrh','743939','5133195211',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Caroline','Wilbur','732670','9043332204',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Abagial','Atwood','722073','5135448101',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Bryce','Drake','708890','5136096551',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Eric','Medley','726553','5134469639',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Eric Medly');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Omar','Sheta','717561','5132884216',NULL,'Savrda',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Avana','Hilton','656484','5132080538',NULL,'Ralph',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Alexander','Taylor','712169','5135166673',NULL,'Savrda',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Amy','Gutman Fuentes','231805','5137069524',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Andrew','Lakes','709925','5139030701',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jonah','Baldwin','732209','5135039819',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Gerald','Cummings','741979','9376201894',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Evan','Frank','682677','5136164462',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Nathan','Mcclellan','671816','5138010896',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Ben','Weber','738234','8127166481',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Ben Webber');
INSERT dbo.TBorrowerAliases (intBorrowerID,strAlias) VALUES (IDENT_CURRENT('dbo.TBorrowers'), 'Benjamin Weber');
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Ethan','Alexander','738862','9298883555',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Allison','Carr','727389','8594468632',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Anthony','Franks','735376','7405046680',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Miles','Landon','687366','5139085744',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Benie','Lumbuambu','699442','8594157196',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Lucy','Wang','727050','5138869513',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Cecil','Payne','721046','5134390888',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Logan','Grever','731464','8593912090',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jesse','Cooper','735841','8018890623',NULL,'Curtis',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Adrian','Bacon','633360','5132649579',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Caleb','Brennan','617633','5134978301',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Tyler','Sansone','721045','5139030996',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Jason','Stanley','676359','5135927216',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Arthur','Viirchanko','749072','5133028713',NULL,'Waley',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Steven','Mose','732042','5138088690',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Daniel','Hoffer','754286','5137065730',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Russ','Wright','745890','5132577539',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Daniel','Kaiser','676443','5137046652',NULL,'Thelson',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Imaed','Boudouma','691755','5138238869',NULL,'Thelson',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Geuillermo','Venegas','755314','3606746762',NULL,'Thelson',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Dontonio','Brown','721661','5139552673',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Cameron','Wallace','656060','5136962861',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Nathaniel','Offei','746378','5136335047',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Erin','Grow','728227','3609222959',NULL,'Ron',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Devin','Ilunga','731773','5138169326',NULL,'Geraldine',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Abygale','Browning','729129','5136735792',NULL,'Feghali',NULL);
INSERT dbo.TBorrowers (strFirstName,strLastName,strSchoolIDNumber,strPhoneNumber,strRoomNumber,strInstructor,intDepartmentID) VALUES ('Vince','Vogel','753628','5135187691',NULL,NULL,NULL);

-- Items
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Everything',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dignity',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dig Kit',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('3 AA batteries',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('IR Unit, Reflector and Buzzer',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer #27',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer #30',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('7400 (NAND)',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Resistors and Orange Board',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainor 26',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Red LED, 7408, 220 Resistor',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Reistors',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Reistors, LED and bread board',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Calculators',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer #41',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('MSP430+USB cable: #1',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('3/32 Collet',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer #15',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('22V10 chips',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dig Trainer 27',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dig Trainer 15',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Instrumentation Kit #06',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dig Trainer #30',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dig Kit (temporary)',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('250ma fuse',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Motor Kit #6',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainor 3',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Display 10, 74LS190',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('7 seg display',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer 3, 7seg display',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('HP charger',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Toolkit 5',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('MSP430 #2',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('bread board',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('MSP430 #1',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Trainer #9',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Instrumentation Kit #5, Breadboard',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Digital Trainer #32',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('motor and control kit 8',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Green extension cable',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Microcontroller #2',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Soldering Kit #17',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('trainer 31 breadboard',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('2 probes +breadboard',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('probes x3',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('7 segment display',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('74190 chip',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('phillips screwdriver',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('trainer #8',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('trainer 31 + temp deg kit',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('7seg',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Chips for personal project',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Motor Kit #3, Multimeter',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Various hookup wires for MSP430',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Tranier #42',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('soldering kit 35',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('solder kit 12, breadboard',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Screwdrivers',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('solder kit #21',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('solder kit #31',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('solder kit 7',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('wire strippers',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('solder kit #01 + 3sponges + bottle',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('temporary dig kit',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('ruler',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('painter''s tape',1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES (NULL,1,NULL,'Material item');
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Ball Mouse',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('HP monitor',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Cooktek cooky thingies',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Lenovo all-in-one',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('DMPS',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell monitor p2212hb',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell monitor p2419h',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell 9010',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('flash drives with cables',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell P2211HT',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('iBuyPower desktop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Fujitsu fi-5120C',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Logo motor controll switch',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('crestron',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('microphone',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Radio/speaker',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Amp',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Precision 3431',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('trainor',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Wire Cart',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('audio wire',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('5.5mm Audio cable',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('buzzer boxes',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('buzzers',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('dell laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell Latitude E6430',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Gateway laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('HP Envy 5530 printer',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Desktop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('TI-84',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('HP PC',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Angle Grinder',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Zephyrus PC',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('HP Laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('PC Mouse',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Surface pro with Wifi Dongle',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('lenovo ideapad 3',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('9010',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('asus Vivobook',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Fujitsu scanner',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('ROG Laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('9020',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('MSI Laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('scanner',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Lenovo laptop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('dell all in one',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('school desktop',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('hp laptop (blue keyboard)',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('samsung a12',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('OS-7020A',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Welder Footpedial',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Power supplie',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Kicker Amp and rockford fosgate amp',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('dell precision 3431',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('label maker',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('dell 9020',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('metal detector',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('hp laptop 15',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Pyle amp',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('dell inspiron 15 5000',1,NULL,NULL);
INSERT dbo.TItems (strItemName, blnIsSchoolOwned, intDepartmentID, strDescription) VALUES ('Dell AiO',1,NULL,NULL);